apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: korifi-controllers-serving-cert
spec:
  dnsNames:
  - korifi-controllers-webhook-service.{{ .Release.Namespace }}.svc
  - korifi-controllers-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: korifi-controllers-selfsigned-issuer
  secretName: webhook-server-cert
