{{- if .Values.debug }}
apiVersion: v1
kind: Service
metadata:
  name: korifi-statefulset-runner-controller-manager-debug-port
spec:
  ports:
  - name: debug-30054
    nodePort: 30054
    port: 30054
    protocol: TCP
    targetPort: 40000
  selector:
    app: korifi-statefulset-runner-controller-manager
  type: NodePort
{{- end }}
