apiVersion: v1
kind: Service
metadata:
  name: korifi-statefulset-runner-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
