apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: korifi-controllers-system

namePrefix: korifi-controllers-

resources:
- ../../../../config
- ../../default

replacements:
- source:
    version: v1
    kind: ConfigMap
    name: config
    fieldPath: data.buildReconciler
  targets:
  - select:
      version: v1
      kind: Deployment
      name: controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].env.[name=BUILD_RECONCILER].value
- source:
    version: v1
    kind: ConfigMap
    name: config
    fieldPath: data.appReconciler
  targets:
  - select:
      version: v1
      kind: Deployment
      name: controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].env.[name=APP_RECONCILER].value
- source:
    version: v1
    kind: ConfigMap
    name: config
    fieldPath: data.processDefaultMemoryMB
  targets:
  - select:
      version: v1
      kind: Deployment
      name: controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].env.[name=PROCESS_DEFAULT_MEMORY_MB].value
- source:
    version: v1
    kind: ConfigMap
    name: config
    fieldPath: data.processDefaultDiskQuotaMB
  targets:
  - select:
      version: v1
      kind: Deployment
      name: controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].env.[name=PROCESS_DEFAULT_DISK_QUOTA_MB].value
- source:
    version: v1
    kind: ConfigMap
    name: config
    fieldPath: data.rootNamespace
  targets:
  - select:
      version: v1
      kind: Deployment
      name: controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].env.[name=ROOT_NAMESPACE].value
  - select:
      version: v1
      kind: Namespace
      name: cf
    fieldPaths:
    - metadata.name
- source:
    version: v1
    kind: ConfigMap
    name: config
    fieldPath: data.packageRegistrySecretName
  targets:
  - select:
      version: v1
      kind: Deployment
      name: controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].env.[name=PACKAGE_REGISTRY_SECRET_NAME].value
- source:
    version: v1
    kind: ConfigMap
    name: config
    fieldPath: data.taskTTL
  targets:
  - select:
      version: v1
      kind: Deployment
      name: controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].env.[name=TASK_TTL].value
- source:
    version: v1
    kind: ConfigMap
    name: config
    fieldPath: data.workloads_tls_secret_name
  targets:
  - select:
      version: v1
      kind: Deployment
      name: controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].env.[name=WORKLOADS_TLS_SECRET_NAME].value
- source:
    version: v1
    kind: ConfigMap
    name: config
    fieldPath: data.workloads_tls_secret_namespace
  targets:
  - select:
      version: v1
      kind: Deployment
      name: controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].env.[name=WORKLOADS_TLS_SECRET_NAMESPACE].value
