apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: korifi-api
  name: deployment
spec:
  template:
    metadata:
      labels:
        app: korifi-api
    spec:
      containers:
      - name: korifi-api
        env:
        - name: EXTERNAL_FQDN
          value: "localhost"
        - name: PACKAGE_REGISTRY_BASE
          value: "localregistry-docker-registry.default.svc.cluster.local:30050/kpack/packages"
        - name: DEFAULT_DOMAIN_NAME
          value: vcap.me
