apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


patchesStrategicMerge:
- deployment-env-var.yaml

patches:
- target:
    group: projectcontour.io
    version: v1
    kind: HTTPProxy
    name: proxy
  patch: |-
    - op: replace
      path: /spec/virtualhost/fqdn
      value: "localhost"
