---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: korifi-controllers-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/status
  - serviceaccounts/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - patch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - appworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - appworkloads/status
  verbs:
  - get
  - patch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - builderinfos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - builderinfos/finalizers
  verbs:
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - builderinfos/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - buildworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - buildworkloads/status
  verbs:
  - get
  - patch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfapps/finalizers
  verbs:
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfapps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfbuilds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfdomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cforgs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cforgs/finalizers
  verbs:
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cforgs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfpackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfpackages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfprocesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfprocesses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfroutes/finalizers
  verbs:
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfservicebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfservicebindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfserviceinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfserviceinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfspaces/finalizers
  verbs:
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cftasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cftasks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - taskworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - taskworkloads/status
  verbs:
  - get
  - patch
- apiGroups:
  - kpack.io
  resources:
  - clusterbuilders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kpack.io
  resources:
  - clusterbuilders/status
  verbs:
  - get
- apiGroups:
  - kpack.io
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - kpack.io
  resources:
  - images/status
  verbs:
  - get
  - patch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - deletecollection
  - patch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies/finalizers
  verbs:
  - update
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies/status
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - servicebinding.io
  resources:
  - servicebindings
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
