apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.k8s.cloudfoundry.org
spec:
  caBundle: |-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURsekNDQW4rZ0F3SUJBZ0lVWTlieDBDaE5J
    UkY2dDlVSW9DbEZLdXljSGRzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0RURUxNQWtHQTFVRUJoTUNT
    VlF3SGhjTk1qSXdNekU0TVRjeU56STJXaGNOTWpJd05ERTNNVGN5TnpJMgpXakFOTVFzd0NRWURW
    UVFHRXdKSlZEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCCkFMR09I
    VUZERVBpUDdxeExsQTZOYjhSeWtLQlBjZ1dKRzY4TGFRS3p6TnpCU1pFNUNPWThQd0c0RUtFTWRQ
    cUYKa3IxdUF2QlJpZ0ZMYmVDV0d2dHJpNW1zVDhWZlJlcVdCdWFRekdoU1ZZaDVzYVlKVWpSRndw
    TnN2dFZHM1NkWApISDJFSXNTWHZEdEtDWkswK1FIZk1FRUxmOFRIN1J6ZUI5SUticmQxc21mRWtr
    WmlmN05oMUpwLyswZVlVVzJBCkpyT0pBemorMnR2cU5UNUdqcVpiZXlpRnpHOXVuWkEvN0FUSmhx
    aXNBb2UwTlM2OHo0UVNNeUpobzMyV1ZmWUcKQ2dsUTZJZjdneTNYZXRCaURvNkNyVC9NWmNKdmN1
    Unl5TnpCamR3dU1wNWJhN1IybDBnSEV5TnBhZ3RQS1dLLwoyRVRnQURLS1gzYldLWjMwZVF3STdl
    OENBd0VBQWFPQjdqQ0I2ekFkQmdOVkhRNEVGZ1FVaTBBNlllc0NPWlFICm5pRUJUMmprRDV6Mkxa
    NHdId1lEVlIwakJCZ3dGb0FVaTBBNlllc0NPWlFIbmlFQlQyamtENXoyTFo0d0R3WUQKVlIwVEFR
    SC9CQVV3QXdFQi96Q0Jsd1lEVlIwUkJJR1BNSUdNZ2c1alppMXJPSE10WVhCcExYTjJZNElnWTJZ
    dAphemh6TFdGd2FTMXpkbU11WTJZdGF6aHpMV0Z3YVMxemVYTjBaVzJDSkdObUxXczRjeTFoY0dr
    dGMzWmpMbU5tCkxXczRjeTFoY0drdGMzbHpkR1Z0TG5OMlk0SXlZMll0YXpoekxXRndhUzF6ZG1N
    dVkyWXRhemh6TFdGd2FTMXoKZVhOMFpXMHVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3dEUVlKS29a
    SWh2Y05BUUVMQlFBRGdnRUJBRE5jZEVnNwpLYXNoMU1VNWNQdFg4eXAzcytEZHQ4VG5ZNWJ0V3lO
    cndWT1ZleWFXU1c4eEEyek1FZkFFWDVtL0w4NXRYR3R6CmpGclNDSDZtcjZVTHV2OXBsK3JZbDNZ
    d1JScFpNWHcvR3piSEEyWEcyL1FZZHd2WkIyU0F0TlV0U0k2WHNQcWoKOWtROUxlV3BjSkZrV1FE
    K0FvVy9udml2QzBRYytycjcrRlpOU2t3dkpPczFrRytrbXJUTzVpOG56UmpYbG9abApZeHBRVSt6
    UmNDNXdFZnR5cjhZMi9TeHlxVzZCWlowdUh6REJNWjNBSDBEL3BLdmNhS2d4MlllTVFBMFNGVVRL
    CkpmTjZsc2RLNWVXd1dNR3JBMFdYUGhYckQwQ1c5RSs0WUU0cDFUbllzNWlEbmJaemhtOXNsT21z
    S0dFQzJGSTMKVWM0NktkRnVQZUVWV2w4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  group: k8s.cloudfoundry.org
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: svc
    namespace: system
  version: v1alpha1
