apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.k8s.cloudfoundry.org
spec:
  caBundle: |-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURsekNDQW4rZ0F3SUJBZ0lVU2N3bVI4YTlT
    KzBhaXZsZFpRQVY0eExvRHQwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0RURUxNQWtHQTFVRUJoTUNT
    VlF3SGhjTk1qSXdNekl5TVRNMU1ETXdXaGNOTWpJd05ESXhNVE0xTURNdwpXakFOTVFzd0NRWURW
    UVFHRXdKSlZEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCCkFNVlg5
    TWxITWoyQzd6MkdiUE5PL1d6SGM0bHZWejlqSEFkdjBKM3VyUXdqaHgrRG8rYnhqMmRiRFZkUnRh
    U2QKT2ZTSm50Um1DalhjNnFQdHNJWFZIN0w4YXZBNXJvbEFIajVON3E4dEJRWlZIUVJMeGloSU9F
    TDR1Sm0vTGVEdQpvb0p0am5DS0puNFZZMFZxM1lRTTRGWldzWUxRVnpJNHM4UzJVaERtVW55Q0lJ
    dmliNEl0SHVLSC9TbWhtK1NJCjR2NFpHb1RFSit5aGx3cWpRZXdTc3o5Q1E1ak5QWGdlRG5GNzNn
    anVzbjh1Q1liUEVyWTNrNkY0Q2Vtdk5ZTzgKSk10OGFaQnpMQVQ5MmxiUS9sL3lUTW1DbENOcUx3
    MTdralhZdWNMcVdoQmE1cGt5cStYV0JKT1NWWlY1eUg5Vgp4SDROTWRDUjl3SWJEWFk1WmxFejhj
    a0NBd0VBQWFPQjdqQ0I2ekFkQmdOVkhRNEVGZ1FVWExKelF0TW5ZZkV2Ckp6U2dqNTJCeDFxbVpa
    VXdId1lEVlIwakJCZ3dGb0FVWExKelF0TW5ZZkV2SnpTZ2o1MkJ4MXFtWlpVd0R3WUQKVlIwVEFR
    SC9CQVV3QXdFQi96Q0Jsd1lEVlIwUkJJR1BNSUdNZ2c1alppMXJPSE10WVhCcExYTjJZNElnWTJZ
    dAphemh6TFdGd2FTMXpkbU11WTJZdGF6aHpMV0Z3YVMxemVYTjBaVzJDSkdObUxXczRjeTFoY0dr
    dGMzWmpMbU5tCkxXczRjeTFoY0drdGMzbHpkR1Z0TG5OMlk0SXlZMll0YXpoekxXRndhUzF6ZG1N
    dVkyWXRhemh6TFdGd2FTMXoKZVhOMFpXMHVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3dEUVlKS29a
    SWh2Y05BUUVMQlFBRGdnRUJBRlhVMEd0dgp0S0phQ2pJbWlUcy9HaFVFTWJtTDdPR3BDQmhkSDh2
    L09IY2RwZDJsQWNKR1dCYUdQUVJjY2tZNlg0YlJNOUZlCldaM2NqL1JrVFhjaGg1cHhrcDZ2ZXVK
    Wk94bXplbFdOc3NJUHFNSUJoZ0diSytyS1lEYmlmbm9oTmE4MEt3d3gKckNMOW1JQjdnM2orWkN1
    Q2ExOG1WU2pDdmJMcGkwazV4Q28veUNMMUVydUVKMUFJeHlmTmhHUUo1aFFJWWN0TApXeGJzM2Uw
    TmhwRHhkai9FU3FOcDVkUW40RDZDZnZOclNRRWpHVVRMZERoUU5VODlMK2F3NW41S1I3dmdzdUZt
    CjVNSi9Xamo4Mkw3UW1iQ0JuS3VwTythZ3dMR3RveXV1RWhrSUgzb1kyYjFEMTBONlZIQWR1YXEz
    TmllUWR3UUgKMHFPcit5eFhzYnl4VE5NPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  group: k8s.cloudfoundry.org
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: svc
    namespace: system
  version: v1alpha1
