apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.k8s.cloudfoundry.org
spec:
  caBundle: |-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURsekNDQW4rZ0F3SUJBZ0lVU2VIMjZLendk
    aVVuNy9jUU95emVCaTVNRWtvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0RURUxNQWtHQTFVRUJoTUNT
    VlF3SGhjTk1qSXdNekl4TVRZek9UQTJXaGNOTWpJd05ESXdNVFl6T1RBMgpXakFOTVFzd0NRWURW
    UVFHRXdKSlZEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCCkFPVnN2
    WXNyMVl0UkJpUW9RT0hFYUl5ZkRib1h3LzRweUkydDh3SnhGeHNjbHZNZEF6eWlRU0xPUEVUb3J5
    QnIKS01GY0lEMWpTKzR4ZEt0YzI0S2FnZnlDUjl3TXBrQUFpTUtPTzh6N0ZoYVNzTHpoL1IzdmpN
    ZDhlSHBpM0F0cwptQ0x4ei91aGdyTCtjR2VCc2NQY1FlcGRxTUVtRnorU1BmWTBGK0xjd01ZMVlE
    cy9iTFE0K3dtNmJ4SmJndERoCnVDR2didFNEYlVrU2h2OG9OQWV6TjBwOGZ2ZHZnekhmVkVWRExZ
    QUZIZ25VZS8rWVN0TkU3LzYxbXJyK2FWZWUKcFZCZ3YvWFZFbVBnYUtCRUYwWms4MjNUdWlqUnlP
    Y041aEpqQjZEOVJjK3lGWEZVaEZieWRBV2NLaFlQeXJZRwo3WXN4UzQ3OU9FMGF3OUgxakE5TnQ2
    Y0NBd0VBQWFPQjdqQ0I2ekFkQmdOVkhRNEVGZ1FVTUtITXV4cjJRRHJPCkNOWUJVZ1JxRjNERGNU
    Y3dId1lEVlIwakJCZ3dGb0FVTUtITXV4cjJRRHJPQ05ZQlVnUnFGM0REY1Rjd0R3WUQKVlIwVEFR
    SC9CQVV3QXdFQi96Q0Jsd1lEVlIwUkJJR1BNSUdNZ2c1alppMXJPSE10WVhCcExYTjJZNElnWTJZ
    dAphemh6TFdGd2FTMXpkbU11WTJZdGF6aHpMV0Z3YVMxemVYTjBaVzJDSkdObUxXczRjeTFoY0dr
    dGMzWmpMbU5tCkxXczRjeTFoY0drdGMzbHpkR1Z0TG5OMlk0SXlZMll0YXpoekxXRndhUzF6ZG1N
    dVkyWXRhemh6TFdGd2FTMXoKZVhOMFpXMHVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3dEUVlKS29a
    SWh2Y05BUUVMQlFBRGdnRUJBRjdZeTlONwpqaUdjVlpZOHNxWXRabjhsUFExNUxuOTNFdC9xOHJy
    eWhteW1OOXRrVGtDbUc5ZFdRNlJreWJ6ZThNanlKcWs5CnlZVDdaam1xR2orRGc0TnRIemdLc1h4
    aU1oRHJIOFZXMHh2T3lsN3RtSExxSGVQdGs3ZTJIa29sc2psK0ErNVoKU3BxRUNsWkZ3U2lYbFFj
    ZWE5UG5KeFlSbHNLZXQ2ZTdWZnI0U09WUTBBYnhTbUE1ZHpzVXpSZXZnVFF3QmdWRgoyM2xCRFJX
    YzRzQmJiL083Z3BtcWtIUjNSZXNKNEpPYU9mVDhpK2I2NEJTT2k2dnJVVjJ5b213ckFlNDZNU1dB
    CnJQckhLaUk0K3dNSEp2VWFWRlZHZHJQZmxJZ2Z3ODlXZllyOHUrOXMyR0gvTDB2ajBDZDJtY3RZ
    b0RlSktZQlMKYzU4QWZTL3drTU5RcjFzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  group: k8s.cloudfoundry.org
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: svc
    namespace: system
  version: v1alpha1
