apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: korifi-api
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: korifi-api
  strategy: {}
  template:
    metadata:
      labels:
        app: korifi-api
    spec:
      serviceAccountName: system-serviceaccount
      containers:
      - image: cloudfoundry/korifi-api:latest
        name: korifi-api
        ports:
        - containerPort: 9000
          name: web
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        env:
        - name: APICONFIG
          value: "/etc/korifi-api-role-mappings"
        - name: TLSCONFIG
          value: "/etc/korifi-tls-config"
        - name: EXTERNAL_FQDN
          value: ""
        - name: INTERNAL_PORT
          value: ""
        - name: ROOT_NAMESPACE
          value: ""
        - name: LIFECYCLE_TYPE
          value: ""
        - name: LIFECYCLE_STACK
          value: ""
        - name: LIFECYCLE_STAGING_MEMORY_MB
          value: ""
        - name: LIFECYCLE_STAGING_DISK_MB
          value: ""
        - name: PACKAGE_REGISTRY_BASE
          value: ""
        - name: PACKAGE_REGISTRY_SECRET
          value: ""
        - name: DEFAULT_DOMAIN_NAME
          value: ""
        volumeMounts:
        - name: &configname korifi-api-role-mappings
          mountPath: /etc/korifi-api-role-mappings
          readOnly: true
        - name: &tlsname korifi-tls-config
          mountPath: /etc/korifi-tls-config
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: *configname
        configMap:
          name: korifi-api-role-mappings
      - name: *tlsname
        secret:
          secretName: korifi-api-internal-cert
