apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: korifi-api
  name: proxy
spec:
  virtualhost:
    fqdn: API_URL
    tls:
      secretName: korifi-api-ingress-cert
  routes:
  - conditions:
    - prefix: /
    services:
    - name: korifi-api-svc
      port: 443
      validation:
        caSecret: korifi-api-internal-cert
        subjectName: $(API_SERVICE_NAME).$(API_SERVICE_NS).svc.cluster.local
    timeoutPolicy:
      response: "5m"
