
resources:
- certificate.yaml
- deployment.yaml
- ingress.yaml
- namespace.yaml
- rbac
- service.yaml

configMapGenerator:
- files:
  - apiconfig/role_mappings_config.yaml
  name: role-mappings

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: cloudfoundry/korifi-api
  newName: cloudfoundry/korifi-api
  newTag: latest

# the following config is for teaching kustomize how to do var substitution
vars:
- fieldref:
    fieldPath: metadata.namespace
  name: API_SERVICE_NS
  objref:
    kind: Service
    name: svc
    version: v1
- fieldref: {}
  name: API_SERVICE_NAME
  objref:
    kind: Service
    name: svc
    version: v1

configurations:
- kustomizeconfig.yaml
