# permissions for end users to view buildreconcilerinfos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buildreconcilerinfo-viewer-role
rules:
- apiGroups:
  - korifi.cloudfoundry.org.cloudfoundry.org
  resources:
  - buildreconcilerinfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - korifi.cloudfoundry.org.cloudfoundry.org
  resources:
  - buildreconcilerinfos/status
  verbs:
  - get
