# permissions for end users to edit buildreconcilerinfos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buildreconcilerinfo-editor-role
rules:
- apiGroups:
  - korifi.cloudfoundry.org.cloudfoundry.org
  resources:
  - buildreconcilerinfos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org.cloudfoundry.org
  resources:
  - buildreconcilerinfos/status
  verbs:
  - get
