# permissions for end users to view cfdomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfdomain-viewer-role
rules:
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfdomains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfdomains/status
  verbs:
  - get
