# permissions for end users to edit cforgs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cforg-editor-role
rules:
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cforgs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cforgs/status
  verbs:
  - get
