# permissions for end users to view cfroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfroute-viewer-role
rules:
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfroutes/status
  verbs:
  - get
