# permissions for end users to edit cfserviceinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfserviceinstance-editor-role
rules:
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfserviceinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cfserviceinstances/status
  verbs:
  - get
