# permissions for end users to edit cftasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cftask-editor-role
rules:
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cftasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cftasks/status
  verbs:
  - get
