externalFQDN: "pinniped-poc-api.cf-for-k8s.relint.rocks"
internalPort: 9000

rootNamespace: cf
defaultLifecycleConfig:
  type: buildpack
  stack: cflinuxfs3
  stagingMemoryMB: 1024
  stagingDiskMB: 1024
packageRegistryBase: gcr.io/cf-relint-greengrass/cf-k8s-controllers/kpack/beta
packageRegistrySecretName: image-registry-credentials # Create this secret in the rootNamespace
clusterBuilderName: cf-kpack-cluster-builder
defaultDomainName: pinniped-poc-apps.cf-for-k8s.relint.rocks
