externalFQDN: api.install.korifi.cf-app.com
internalPort: 9000

rootNamespace: cf
defaultLifecycleConfig:
  type: buildpack
  stack: cflinuxfs3
  stagingMemoryMB: 1024
  stagingDiskMB: 1024
packageRegistryBase: europe-west6-docker.pkg.dev/cf-on-k8s-wg/installation-test
packageRegistrySecretName: image-registry-credentials # Create this secret in the rootNamespace
clusterBuilderName: cf-kpack-cluster-builder
defaultDomainName: apps.install.korifi.cf-app.com
