---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: eirini-x-mutating-hook
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/webhook-cert"
webhooks:
- name: instance-index-env-injector.eirini.cloudfoundry.org
  objectSelector:
    matchLabels:
      korifi.cloudfoundry.org/source-type: APP
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["pods"]
    scope: "Namespaced"
  clientConfig:
    service:
      namespace: "{{ .Release.Namespace }}"
      name: eirini-webhooks
      path: "/"
  admissionReviewVersions: ["v1beta1"]
  sideEffects: None
  timeoutSeconds: 10

