externalFQDN: 127.0.0.1:38241/apis/k8s.cloudfoundry.org/v1alpha1/cf
internalPort: 0

rootNamespace: cf
defaultLifecycleConfig:
  type: buildpack
  stack: cflinuxfs3
  stagingMemoryMB: 1024
  stagingDiskMB: 1024
packageRegistryBase: localregistry-docker-registry.default.svc.cluster.local:30050/kpack/packages
packageRegistrySecretName: image-registry-credentials
authEnabled: true
clusterBuilderName: cf-kpack-cluster-builder
defaultDomainName: vcap.me
