---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: build-supply-chain
spec:
  selector:
    workloads.cloudfoundry.org/workload-type: cf-build
  resources:
    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: image
  serviceAccountRef:
    name: cf-k8s-controllers-controller-manager
    namespace: cf-k8s-controllers-system
