---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: workloads-fallback-delegation
spec:
  delegations:
    - secretName: korifi-workloads-ingress-cert
      targetNamespaces:
        - "*"
