apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korifi-controllers-organization-manager
rules:
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - cforgs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - korifi.cloudfoundry.org
  resources:
  - buildreconcilerinfos
  verbs:
  - get
  - list
  - watch
