apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/korifi-controllers-serving-cert
  name: korifi-controllers-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: korifi-controllers-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-korifi-cloudfoundry-org-v1alpha1-cfdomain
  failurePolicy: Fail
  name: vcfdomain.korifi.cloudfoundry.org
  rules:
  - apiGroups:
    - korifi.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cfdomains
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: korifi-controllers-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-korifi-cloudfoundry-org-v1alpha1-cfroute
  failurePolicy: Fail
  name: vcfroute.korifi.cloudfoundry.org
  rules:
  - apiGroups:
    - korifi.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - cfroutes
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: korifi-controllers-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-korifi-cloudfoundry-org-v1alpha1-cfservicebinding
  failurePolicy: Fail
  name: vcfservicebinding.korifi.cloudfoundry.org
  rules:
  - apiGroups:
    - korifi.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - cfservicebindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: korifi-controllers-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-korifi-cloudfoundry-org-v1alpha1-cfserviceinstance
  failurePolicy: Fail
  name: vcfserviceinstance.korifi.cloudfoundry.org
  rules:
  - apiGroups:
    - korifi.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - cfserviceinstances
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: korifi-controllers-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-korifi-cloudfoundry-org-v1alpha1-cfapp
  failurePolicy: Fail
  name: vcfapp.korifi.cloudfoundry.org
  rules:
  - apiGroups:
    - korifi.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - cfapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: korifi-controllers-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-korifi-cloudfoundry-org-v1alpha1-cforg
  failurePolicy: Fail
  name: vcforg.korifi.cloudfoundry.org
  rules:
  - apiGroups:
    - korifi.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - cforgs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: korifi-controllers-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-korifi-cloudfoundry-org-v1alpha1-cfspace
  failurePolicy: Fail
  name: vcfspace.korifi.cloudfoundry.org
  rules:
  - apiGroups:
    - korifi.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - cfspaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: korifi-controllers-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-korifi-cloudfoundry-org-v1alpha1-cftask
  failurePolicy: Fail
  name: vcftask.korifi.cloudfoundry.org
  rules:
  - apiGroups:
    - korifi.cloudfoundry.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cftasks
  sideEffects: None
