global:
  rootNamespace: cf
  debug: false
  defaultAppDomainName: apps.my-cf-domain.com
  packageRegistrySecret: image-registry-credentials

include: true
namespace: korifi-controllers-system
replicas: 1
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 100Mi

image: cloudfoundry/korifi-controllers:latest
reconcilers:
  build: kpack-image-builder
  app: statefulset-runner
processDefaults:
  memoryMB: 1024
  diskQuotaMB: 1024
taskTTL: 30d

# istio's sidecar requires additional capabilities and cannot start if pod
# security standards are enforced. When using istio we should switch
# enforcement off.
enforcePodSecurityStandards: false
