---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: space-auditor
rules:
- apiGroups:
  - kpack.io
  resources:
  - clusterbuilders
  verbs:
  - get
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfapps
  verbs:
  - get
  - list
