# The following patch adds a directive for certmanager to inject CA into the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(SSR_CERTIFICATE_NAMESPACE)/$(SSR_CERTIFICATE_NAME)
  name: appworkloads.ext.cloudfoundry.org
