---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-cache
  namespace: eirini-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
