#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: #@ data.values.controllers.cfRootNamespace
secrets:
- name: #@ data.values.controllers.packageRegistrySecretName
imagePullSecrets:
  - name: #@ data.values.controllers.packageRegistrySecretName
