apiVersion: v1
kind: Namespace
metadata:
  name: cf-k8s-api-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-k8s-api-cf-admin-serviceaccount
  namespace: cf-k8s-api-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cf-k8s-api-cf-admin-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/status
  - serviceaccounts/status
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - hnc.x-k8s.io
  resources:
  - hierarchyconfigurations
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - hnc.x-k8s.io
  resources:
  - subnamespaceanchors
  verbs:
  - create
  - delete
  - list
  - watch
- apiGroups:
  - kpack.io
  resources:
  - clusterbuilders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kpack.io
  resources:
  - clusterbuilders/status
  verbs:
  - get
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - cfdomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - cfdomains/status
  verbs:
  - get
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - cfroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloudfoundry.org
  resources:
  - cfroutes/status
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - list
- apiGroups:
  - services.cloudfoundry.org
  resources:
  - cfservicebindings
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - services.cloudfoundry.org
  resources:
  - cfserviceinstances
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfapps/status
  verbs:
  - get
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfbuilds/status
  verbs:
  - get
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfpackages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfpackages/status
  verbs:
  - get
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfprocesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.cloudfoundry.org
  resources:
  - cfprocesses/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cf-k8s-api-cf-admin-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cf-k8s-api-cf-admin-clusterrole
subjects:
- kind: ServiceAccount
  name: cf-k8s-api-cf-admin-serviceaccount
  namespace: cf-k8s-api-system
---
apiVersion: v1
data:
  cf_k8s_api_config.yaml: |
    externalFQDN: "api.example.org"
    internalPort: 9000

    rootNamespace: cf
    defaultLifecycleConfig:
      type: buildpack
      stack: cflinuxfs3
      stagingMemoryMB: 1024
      stagingDiskMB: 1024
    packageRegistryBase: gcr.io/cf-relint-greengrass/cf-k8s-controllers/kpack/beta
    packageRegistrySecretName: image-registry-credentials # Create this secret in the rootNamespace
    clusterBuilderName: cf-kpack-cluster-builder
    defaultDomainName: apps.example.org
  role_mappings_config.yaml: |
    roleMappings:
      admin:
        name: cf-k8s-controllers-admin
        propagate: true
      admin_read_only:
        name: cf-k8s-controllers-admin-read-only
        propagate: true
      cf_user:
        name: cf-k8s-controllers-root-namespace-user
        propagate: false
      global_auditor:
        name: cf-k8s-controllers-global-auditor
        propagate: true
      organization_auditor:
        name: cf-k8s-controllers-organization-auditor
        propagate: false
      organization_billing_manager:
        name: cf-k8s-controllers-organization-billing-manager
        propagate: false
      organization_manager:
        name: cf-k8s-controllers-organization-manager
        propagate: true
      organization_user:
        name: cf-k8s-controllers-organization-user
        propagate: false
      space_auditor:
        name: cf-k8s-controllers-space-auditor
        propagate: false
      space_developer:
        name: cf-k8s-controllers-space-developer
        propagate: false
      space_manager:
        name: cf-k8s-controllers-space-manager
        propagate: false
      space_supporter:
        name: cf-k8s-controllers-space-supporter
        propagate: false
kind: ConfigMap
metadata:
  name: cf-k8s-api-config-446hhfhb5b
  namespace: cf-k8s-api-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cf-k8s-api
  name: cf-k8s-api-svc
  namespace: cf-k8s-api-system
spec:
  ports:
  - name: web
    port: 443
    protocol: TCP
    targetPort: web
  selector:
    app: cf-k8s-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cf-k8s-api
  name: cf-k8s-api-deployment
  namespace: cf-k8s-api-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cf-k8s-api
  strategy: {}
  template:
    metadata:
      labels:
        app: cf-k8s-api
    spec:
      containers:
      - env:
        - name: APICONFIG
          value: /etc/cf-k8s-api-config
        image: cloudfoundry/cf-k8s-api:latest
        name: cf-k8s-api
        ports:
        - containerPort: 9000
          name: web
        resources: {}
        volumeMounts:
        - mountPath: /etc/cf-k8s-api-config
          name: cf-k8s-api-config
          readOnly: true
        - mountPath: /etc/server-cert
          name: server-cert-vol
          readOnly: true
      serviceAccountName: cf-k8s-api-cf-admin-serviceaccount
      volumes:
      - configMap:
          name: cf-k8s-api-config-446hhfhb5b
        name: cf-k8s-api-config
      - name: server-cert-vol
        secret:
          optional: false
          secretName: server-cert
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.k8s.cloudfoundry.org
spec:
  caBundle: |-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURsekNDQW4rZ0F3SUJBZ0lVWTlieDBDaE5J
    UkY2dDlVSW9DbEZLdXljSGRzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0RURUxNQWtHQTFVRUJoTUNT
    VlF3SGhjTk1qSXdNekU0TVRjeU56STJXaGNOTWpJd05ERTNNVGN5TnpJMgpXakFOTVFzd0NRWURW
    UVFHRXdKSlZEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCCkFMR09I
    VUZERVBpUDdxeExsQTZOYjhSeWtLQlBjZ1dKRzY4TGFRS3p6TnpCU1pFNUNPWThQd0c0RUtFTWRQ
    cUYKa3IxdUF2QlJpZ0ZMYmVDV0d2dHJpNW1zVDhWZlJlcVdCdWFRekdoU1ZZaDVzYVlKVWpSRndw
    TnN2dFZHM1NkWApISDJFSXNTWHZEdEtDWkswK1FIZk1FRUxmOFRIN1J6ZUI5SUticmQxc21mRWtr
    WmlmN05oMUpwLyswZVlVVzJBCkpyT0pBemorMnR2cU5UNUdqcVpiZXlpRnpHOXVuWkEvN0FUSmhx
    aXNBb2UwTlM2OHo0UVNNeUpobzMyV1ZmWUcKQ2dsUTZJZjdneTNYZXRCaURvNkNyVC9NWmNKdmN1
    Unl5TnpCamR3dU1wNWJhN1IybDBnSEV5TnBhZ3RQS1dLLwoyRVRnQURLS1gzYldLWjMwZVF3STdl
    OENBd0VBQWFPQjdqQ0I2ekFkQmdOVkhRNEVGZ1FVaTBBNlllc0NPWlFICm5pRUJUMmprRDV6Mkxa
    NHdId1lEVlIwakJCZ3dGb0FVaTBBNlllc0NPWlFIbmlFQlQyamtENXoyTFo0d0R3WUQKVlIwVEFR
    SC9CQVV3QXdFQi96Q0Jsd1lEVlIwUkJJR1BNSUdNZ2c1alppMXJPSE10WVhCcExYTjJZNElnWTJZ
    dAphemh6TFdGd2FTMXpkbU11WTJZdGF6aHpMV0Z3YVMxemVYTjBaVzJDSkdObUxXczRjeTFoY0dr
    dGMzWmpMbU5tCkxXczRjeTFoY0drdGMzbHpkR1Z0TG5OMlk0SXlZMll0YXpoekxXRndhUzF6ZG1N
    dVkyWXRhemh6TFdGd2FTMXoKZVhOMFpXMHVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3dEUVlKS29a
    SWh2Y05BUUVMQlFBRGdnRUJBRE5jZEVnNwpLYXNoMU1VNWNQdFg4eXAzcytEZHQ4VG5ZNWJ0V3lO
    cndWT1ZleWFXU1c4eEEyek1FZkFFWDVtL0w4NXRYR3R6CmpGclNDSDZtcjZVTHV2OXBsK3JZbDNZ
    d1JScFpNWHcvR3piSEEyWEcyL1FZZHd2WkIyU0F0TlV0U0k2WHNQcWoKOWtROUxlV3BjSkZrV1FE
    K0FvVy9udml2QzBRYytycjcrRlpOU2t3dkpPczFrRytrbXJUTzVpOG56UmpYbG9abApZeHBRVSt6
    UmNDNXdFZnR5cjhZMi9TeHlxVzZCWlowdUh6REJNWjNBSDBEL3BLdmNhS2d4MlllTVFBMFNGVVRL
    CkpmTjZsc2RLNWVXd1dNR3JBMFdYUGhYckQwQ1c5RSs0WUU0cDFUbllzNWlEbmJaemhtOXNsT21z
    S0dFQzJGSTMKVWM0NktkRnVQZUVWV2w4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  group: k8s.cloudfoundry.org
  groupPriorityMinimum: 1000
  service:
    name: cf-k8s-api-svc
    namespace: cf-k8s-api-system
  version: v1alpha1
  versionPriority: 15
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: cf-k8s-api
  name: cf-k8s-api-proxy
  namespace: cf-k8s-api-system
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: cf-k8s-api-svc
      port: 443
    timeoutPolicy:
      response: 5m
  virtualhost:
    fqdn: ""
    tls:
      secretName: cf-k8s-api-ingress-cert
