apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - args:
        - "--health-probe-bind-address=:8081"
        - "--metrics-bind-address=127.0.0.1:8080"
        - "--leader-elect"
        image: cloudfoundry/korifi-controllers:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 100Mi
        env:
        - name: BUILD_RECONCILER
          value: kpack-image-builder
        - name: APP_RECONCILER
          value: statefulset-runner
        - name: PROCESS_DEFAULT_MEMORY_MB
          value: "1024"
        - name: PROCESS_DEFAULT_DISK_QUOTA_MB
          value: "1024"
        - name: ROOT_NAMESPACE
          value: cf
        - name: PACKAGE_REGISTRY_SECRET_NAME
          value: image-registry-credentials
        - name: TASK_TTL
          value: 30d
        - name: WORKLOADS_TLS_SECRET_NAME
          value: korifi-workloads-ingress-cert
        - name: WORKLOADS_TLS_SECRET_NAMESPACE
          value: korifi-controllers-system
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
