# Will need to duplicate across all namespaces where we build images
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-builder-rolebinding
  namespace: <put your space guid here>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-builder-clusterrole
subjects:
- kind: ServiceAccount
  name: kpack-service-account
  # IMPORTANT!
  namespace: <put your space guid here>
