{{- if .Values.global.generateIngressCertificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: korifi-api-ingress-cert
  namespace: istio-system
spec:
  commonName: "*.{{ .Values.global.defaultAppDomainName }}"
  dnsNames:
  - "*.{{ .Values.global.defaultAppDomainName }}"
  issuerRef:
    kind: Issuer
    name: korifi-api-selfsigned-issuer
  secretName: korifi-api-ingress-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: korifi-api-selfsigned-issuer
  namespace: istio-system
spec:
  selfSigned: {}
{{- end }}
