{{/* apiVersion: projectcontour.io/v1 */}}
{{/* kind: HTTPProxy */}}
{{/* metadata: */}}
{{/*   labels: */}}
{{/*     app: korifi-api */}}
{{/*   name: korifi-api-proxy */}}
{{/*   namespace: {{ .Values.namespace }} */}}
{{/* spec: */}}
{{/*   routes: */}}
{{/*   - conditions: */}}
{{/*     - prefix: / */}}
{{/*     services: */}}
{{/*     - name: korifi-api-svc */}}
{{/*       port: 443 */}}
{{/*       validation: */}}
{{/*         caSecret: korifi-api-internal-cert */}}
{{/*         subjectName: korifi-api-svc.{{ .Values.namespace }}.svc.cluster.local */}}
{{/*     timeoutPolicy: */}}
{{/*       response: 5m */}}
{{/*   virtualhost: */}}
{{/*     fqdn: {{ .Values.apiServer.url }} */}}
{{/*     tls: */}}
{{/*       secretName: korifi-api-ingress-cert */}}


apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: {{ .Values.namespace }}
  name: korifi-api-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: {{ .Values.namespace }}
  name: korifi-api
spec:
  hosts:
  - "*"
  gateways:
  - korifi-api-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: korifi-api-svc
        port:
          number: 80
