apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: {{ ternary "privileged" "restricted" .Values.global.debug }}
    pod-security.kubernetes.io/enforce: {{ ternary "privileged" "restricted" .Values.global.debug }}
    istio-injection: enabled
  name: {{ .Values.namespace }}
