name: Run Tests on PR

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
    - '.*'

jobs:
  check-reference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17' # The Go version to download (if necessary) and use.
      - name: Check for reference yaml drift
        run: |
          make build-reference
          git diff --exit-code

  run-envtest:
    needs: check-reference
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Populate go cache
        run: GOCACHE=.cache/go-build make build
      - name: Save go cache
        uses: actions/cache@v2
        with:
          path: .cache/go-build
          key: ${{ runner.os }}-go-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-go-cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: cloudfoundry/cf-k8s-controllers:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
